---

- name: Create NFS share directory
  ansible.builtin.file:
    path: /srv/nfs
    state: directory
    mode: '0755'
    owner: nobody
    group: nogroup
  become: yes

- name: Copy example file
  ansible.builtin.copy:
    src: www_index.html
    dest: /srv/nfs/index.html
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Copy NFS exports
  ansible.builtin.template:
    src: nfs_exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  become: yes