---

- name: Copy kubeadm init configuration
  ansible.builtin.template:
    src: kubeadm-config.yaml.j2
    dest: /tmp/kubeadm-config.yaml
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Launch control plane with kubeadm
  ansible.builtin.command: kubeadm join --config /tmp/kubeadm-config.yaml
  become: yes