---

- name: Generate kubeadm bootstrap token
  ansible.builtin.command: kubeadm token generate
  register: kubeadm_token
  become: yes

- name: Store kubeadm bootstrap token
  ansible.builtin.set_fact:
    fact_kubeadm_token: "{{ kubeadm_token.stdout }}"

- name: Copy kubeadm init configuration
  ansible.builtin.template:
    src: kubeadm-config.yaml.j2
    dest: /tmp/kubeadm-config.yaml
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Launch control plane with kubeadm
  ansible.builtin.command: kubeadm init --config /tmp/kubeadm-config.yaml
  become: yes

- name: Create k8s home directory
  ansible.builtin.file:
    path: /home/azadmin/.kube
    state: directory
    mode: '0755'
    owner: azadmin
    group: azadmin

- name: Copy k8s admin config
  ansible.builtin.copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: /home/azadmin/.kube/config
    owner: azadmin
    group: azadmin
    mode: '0600'
  become: yes
